### ISSUE TITLE
Broken on Ubuntu

### ISSUE THREAD

**Issue by robbanp** [andrewpuch/code_deploy_example#1]
Hi, this guide is great, but a bit broken on Ubuntu.
1. The ruby path in install is static. I needed to change it to my local path
2. problems installing the deb package. I had to manually download it and execute the installation

I got:

```
sudo ./install auto
I, [2015-06-02T08:59:20.962270 #8138]  INFO -- : Starting update check.
I, [2015-06-02T08:59:20.962547 #8138]  INFO -- : Attempting to automatically detect supported package manager type for system...
I, [2015-06-02T08:59:20.967925 #8138]  INFO -- : Checking AWS_REGION environment variable for region information...
I, [2015-06-02T08:59:20.968048 #8138]  INFO -- : Checking EC2 metadata service for region information...
I, [2015-06-02T08:59:20.986586 #8138]  INFO -- : Downloading version file from bucket aws-codedeploy-eu-west-1 and key latest/VERSION...
I, [2015-06-02T08:59:21.018990 #8138]  INFO -- : Downloading package from bucket aws-codedeploy-eu-west-1 and key releases/codedeploy-agent_1.0-1.719_all.deb...
I, [2015-06-02T08:59:21.019229 #8138]  INFO -- : Downloading from uri https://s3-eu-west-1.amazonaws.com/aws-codedeploy-eu-west-1/releases/codedeploy-agent_1.0-1.719_all.deb...
I, [2015-06-02T08:59:21.096089 #8138]  INFO -- : Executing `/usr/bin/gdebi -n -o Dpkg::Options::="--force-confdef" -o Dpg::Options::="--force-conffold" /tmp/codedeploy-agent_1.0-1.719_all.deb`...
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Building data structures... Done 
Building data structures... Done 
Fetched 0 B in 0s (0 B/s)                                                                                                                                                           
dpkg: error: need an action option

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
Error in function: 
SystemError: E:Sub-process /usr/bin/dpkg returned an error code (2)
Error during install: 'installArchives() failed'E, [2015-06-02T08:59:23.414849 #8138] ERROR -- : Error installing /tmp/codedeploy-agent_1.0-1.719_all.deb.
```

Also it should more clearly state what access keys to enter. Whats the purpose of the access keys. Download from S3 only?

Thanks!

**Comment by andrewpuch** [comment]
Although I haven't fully tested on Ubuntu it's possible it only works with the AWS AMI. Could you try that and let me know what happens? You'll need your access keys on the server so code deploy can correctly talk with your network.

**Comment by robbanp** [comment]
Yeah, I got it to work by manually install the deb package.
What does "code deploy can correctly talk with your network" mean? :smile: 
It would be great to have it specified what needs to be accessed, so the AIM user can be as limited as possible.

**Comment by andrewpuch** [comment]
You can setup autoscaling with it as well as deploy your code out to S3 and it would need access to that. You can definitely secure it down even more :) all depends on what you want to do with it!

**Comment by robbanp** [comment]
Ah, I see. So to clarify, there could be a list of possible things the user can do, and which it would need access to!

Sounds good :)

**Comment by andrewpuch** [comment]
Yep! 100%! I just gave the basics of what most users would like to use it for but you could really use it for alot of different purposes.

**Comment by karthiksjm** [comment]
Andrew.. Awesome..!! 
checked your videos on youtube, about aws code deploy, you made it very simple and clear. i love it.

when i try to do it on one of my AWS instance (which is running on RHEL), i got an broken link message while installing 'code deploy engine'. for your reference,

[root@ip-172-31-16-59 ec2-user]# ./install auto
I, [2015-07-24T11:29:09.503585 #11473]  INFO -- : Starting Ruby version check.
I, [2015-07-24T11:29:09.503769 #11473]  INFO -- : Starting update check.
I, [2015-07-24T11:29:09.503813 #11473]  INFO -- : Attempting to automatically detect supported package manager type for system...
I, [2015-07-24T11:29:09.575378 #11473]  INFO -- : Checking AWS_REGION environment variable for region information...
I, [2015-07-24T11:29:09.575450 #11473]  INFO -- : Checking EC2 metadata service for region information...
I, [2015-07-24T11:29:09.596037 #11473]  INFO -- : Downloading version file from bucket aws-codedeploy-ap-southeast-1 and key latest/VERSION...
E, [2015-07-24T11:29:09.643172 #11473] ERROR -- : Could not find version file to download at 'https://s3-ap-southeast-1.amazonaws.com/aws-codedeploy-ap-southeast-1/latest/VERSION'

can you help me in this regard. 

Thanks
Karthik :-)

**Comment by andrewpuch** [comment]
Karthik I believe it is not offered in that region. Try it in us-east and see if it works.

**Comment by karthiksjm** [comment]
Hi Andrew,
Thanks a lot. it works well. :+1:

**Comment by joshbedo** [comment]
@andrewpuch @robbanp So i'm pretty confused i had this issue on my ubuntu instance and now the amazon linux ami. I'm after the steps i'm trying to run `./install auto` or `sudo ./install auto` and i keep getting `permission denied` or `sudo: unrecognized command ./install`. any ideas?

![](http://i.imgur.com/QPmwIWp.png)

**Comment by joshbedo** [comment]
Got it running, i had to do `chmod -R 777 ./install` to get it working.

**Comment by andrewpuch** [comment]
Awesome great!!!

**Comment by cwurtz** [comment]
I ran into the same error this morning when it tried installing the codedeploy-agent .deb file.  I had originally installed ruby with rvm on the instance (which may or may not have been the case with robbanp).  I was trying to install with `rvmsudo ruby ./install auto`.  I decided to try rebuilding the box, and installed ruby 2.0 with apt-get, and this time the code deploy agent installed fine running `sudo ./install auto`.  Just figured I would mention incase someone else runs into the same problem.

**Comment by andrewpuch** [comment]
Thanks for mentioning that @cwurtz :)

**Comment by toniton** [comment]
I get this error when i try to install aws codedeploy-agent, please help!!!.

`ERROR -- : Error installing /tmp/codedeploy-agent_1.0-1.1106_all.tmp-20170810-25595-ar9c9i.deb.`

The full error message is below:
```
ubuntu@ip-172-31-25-3:~$ sudo ./install deb
I, [2017-08-10T07:19:41.516349 #25595]  INFO -- : Starting Ruby version check.
I, [2017-08-10T07:19:41.516536 #25595]  INFO -- : Starting update check.
I, [2017-08-10T07:19:41.516625 #25595]  INFO -- : Checking AWS_REGION environment variable for region information...
I, [2017-08-10T07:19:41.516691 #25595]  INFO -- : Checking EC2 metadata service for region information...
dpkg-query: package 'codedeploy-agent' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
I, [2017-08-10T07:19:41.550710 #25595]  INFO -- : Running version No running version
I, [2017-08-10T07:19:41.550816 #25595]  INFO -- : Downloading version file from bucket aws-codedeploy-us-west-2 and key latest/VERSION...
I, [2017-08-10T07:19:41.606650 #25595]  INFO -- : Downloading version file from bucket aws-codedeploy-us-west-2 and key latest/VERSION...
I, [2017-08-10T07:19:41.711840 #25595]  INFO -- : Downloading package from bucket aws-codedeploy-us-west-2 and key releases/codedeploy-agent_1.0-1.1106_all.deb...
I, [2017-08-10T07:19:41.827177 #25595]  INFO -- : Executing `/usr/bin/gdebi -n -o Dpkg::Options::=--force-confdef -o Dkpg::Options::=--force-confold /tmp/codedeploy-agent_1.0-1.1106_all.tmp-20170810-25595-ar9c9i.deb`...
E, [2017-08-10T07:19:41.828088 #25595] ERROR -- : Error installing /tmp/codedeploy-agent_1.0-1.1106_all.tmp-20170810-25595-ar9c9i.deb.
```
